### ISSUE TITLE
the bundle fail to execute if there's `noexec` flag on `/tmp` volume

### ISSUE THREAD

**Issue by yihuang** [3noch/nix-bundle-exe#10]
Some clients add the `noexec` flag to the `/tmp` volume, who will get a `Permission denied` when executing, because we move the dynamic linker to `/tmp`.
Any ideas on this? bundle the `patchelf` and patch the elf on the fly? 😂

**Comment by yihuang** [comment]
we'll need to staticly link the patchelf then.

**Comment by 3noch** [comment]
Yes, this can be done easily by depending on `pkgs.pkgsStatic.patchelf`.

**Comment by yihuang** [comment]
`pkgsStatic` doesn't work on macos, right? 
I guess alternatively I can also distribute static binaries for Linux and bundled one for mac.

**Comment by yihuang** [comment]
> Yes, this can be done easily by depending on `pkgs.pkgsStatic.patchelf`.

one shortcoming of running `patchelf` on the fly is the exe file must be writable, which is not the case when running from nix store directly.

**Comment by 3noch** [comment]
Good point. I have wanted to change patchelf to be able to fork the modified process from memory somehow. That would be a much better solution.

Can we use chroot instead without breaking the CLI API of wrapped tools?

**Comment by yihuang** [comment]
> Can we use chroot instead without breaking the CLI API of wrapped tools?

https://github.com/matthewbauer/nix-bundle

do you mean this bundle tool?

**Comment by 3noch** [comment]
It does. But it has other complexities too. If you need a quick solution, I'd try that first for Linux. I wrote this tool primarily for macOS and only decided to try Linux support too as a bonus. I'd still like to make it work for your case, but I'm not spending lots of time on this problem currently.

**Comment by 3noch** [comment]
Thanks to your findings, I added this note to the `README.md` to make the current status of Linux support clearer: https://github.com/3noch/nix-bundle-exe/commit/9378d6b385cfbd015f07d60d406bd58d3b24ddf6

**Comment by 3noch** [comment]
Does #11 fix your issue?

**Comment by yihuang** [comment]
Another issue, the dns resolver failed with error "lookup localhost: device or resource busy", `strace` shows it fail to load some dynamic libraries like `exe/../lib/libnss_files.so.2`, `exe/../lib/libnss_dns.so.2`.
Can work around with `LD_LIBRARY_PATH=/path/to/bundle/lib:/usr/lib/aarch64-linux-gnu`.

**Comment by 3noch** [comment]
Can you file that as a separate issue and provide some details?
