### ISSUE TITLE
The bundled binary failed to call dns resolver

### ISSUE THREAD

**Issue by yihuang** [3noch/nix-bundle-exe#14]
Another issue, the dns resolver failed with error "lookup localhost: device or resource busy", `strace` shows it fail to load some dynamic libraries like `exe/../lib/libnss_files.so.2`, `exe/../lib/libnss_dns.so.2`.
Can work around with `LD_LIBRARY_PATH=/path/to/bundle/lib:/usr/lib/aarch64-linux-gnu`.

part of strace logs:

```
33230 03:16:19.046628 openat(AT_FDCWD, "/chain/.cronosd/cosmovisor/genesis/exe/../lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000015>
33230 03:16:19.046669 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.046708 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/aarch64/atomics/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.046746 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/aarch64/atomics", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.046783 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/aarch64/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.046821 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/aarch64", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.046858 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/atomics/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.046896 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/atomics", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.046933 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.046971 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/tls", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.047008 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/aarch64/atomics/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.047045 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/aarch64/atomics", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.047082 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/aarch64/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.047120 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/aarch64", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.047157 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/atomics/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000013>
33230 03:16:19.047194 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/atomics", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.047231 openat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib/libnss_dns.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory) <0.000014>
33230 03:16:19.047273 newfstatat(AT_FDCWD, "/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-glibc-2.33-123/lib", 0xffffc37724d0, 0) = -1 ENOENT (No such file or directory) <0.000012>
33230 03:16:19.047316 futex(0x4000092950, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
33232 03:16:19.047338 <... futex resumed>) = 0 <0.002249>
33230 03:16:19.047347 <... futex resumed>) = 1 <0.000025>
33232 03:16:19.047357 nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
33230 03:16:19.047397 write(2, "Error: post failed: Post \"http:/"..., 103) = 103 <0.000023>
```

**Comment by 3noch** [comment]
Can you share what you're trying to bundle so I can try to reproduce?

**Comment by 3noch** [comment]
Something is being `nuke-ref`ed that should have been copied and patched instead :thinking:

**Comment by yihuang** [comment]
> Can you share what you're trying to bundle so I can try to reproduce?

https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.0
the rocksdb version binares here is bundled this way, it's a golang application. the `libnss_*.so` are indeed not show up in `ldd` output, I guess they are really dynamically loaded somehow.

**Comment by 3noch** [comment]
Ah interesting. Yes if `patchelf --print-needed` is not reporting these as dependencies then my bundler doesn't know it should be bundling them. But I also don't have a reliable way to replace those paths in the exe with ones from my bundle (are they just strings compiled into the exe?). However, since I `nuke-refs` on these binaries, they no longer have the correct nix paths either.

This is a situation where `nix-bundle` would probably do a better job. It uses `chroot` so that binaries don't need to be modified at all and therefore it work work with just about any situation. The downside, of course, is that it doesn't work on macOS.

**Comment by 3noch** [comment]
If you feel this tool is still a better than `nix-bundle`, then we can discuss stop-gap measures to make it work better.

**Comment by yihuang** [comment]
> If you feel this tool is still a better fit than `nix-bundle`, then we can discuss stop-gap measures to make it work better for these kinds of cases.

I think your approach is still simpler and less magical than the `nix-bundle`.
We can always mitigate the dns resolver issue by enable golang resolver at build time, I'll probably investigate the issue later to see what happened and if there's a solution to the root cause.
Regarding the recent interpreter change, it seems to work on some machines that we had libc version conflicts previously. I'm trying to understand the portability implication of that, the `ldd` shows:
```
interpreter => /lib64/ld-linux-x86-64.so.2
```
So I guess it always use the system builtin linker, right?

**Comment by 3noch** [comment]
Trying running the exe directly and it shouldn't work. At least that's what I observed. The wrapper script ensures the correct interpreter is used.

**Comment by yihuang** [comment]
> Trying running the exe directly and it shouldn't work. At least that's what I observed. The wrapper script ensures the correct interpreter is used.

oh, I see, nice trick.
```
exec /path/to/ld-linux.so /path/to/exe
```

**Comment by 3noch** [comment]
Yep. Obviously should have done it that way to begin with!

I also observed `ldd` "guessing" what the full path was, but I think `ldd` is just wrong.

**Comment by yihuang** [comment]
For the libnss dynamic modules, I guess user can always add extra arbitrary files into the bundle by wrap or override the derivative. I'll close this issue for now.
